fixed 0-run script

diff --git a/0x00-python-hello_world/0-run b/0x00-python-hello_world/0-run
--- a/0x00-python-hello_world/0-run
+++ b/0x00-python-hello_world/0-run
@@ -1,13 +1,2 @@
 #!/bin/bash
-
-if [ -z "$PYFILE" ]; then
-    echo "Error: PYFILE environment variable is not set."
-    exit 1
-fi
-
-if [ ! -f "$PYFILE" ]; then
-    echo "Error: Python file '$PYFILE' not found."
-    exit 1
-fi
-
-python3 "$PYFILE"
+[ -z "$PYFILE" ] && { echo "Error: PYFILE environment variable is not set."; exit 1; } ; python3 "$PYFILE"
